ri_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - base_to_first
    - first_to_second_pivot
    - second_to_third_pivot
    - third_to_effector_pivot
  gains:
    base_to_first:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    first_to_second_pivot:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    second_to_third_pivot:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    third_to_effector_pivot:
      p: 100
      d: 1
      i: 1
      i_clamp: 1